source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

gem "rails", "~> 7.0.2", ">= 7.0.2.2"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem 'seed_dump'
gem 'rswag'
gem 'rack-cors'
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails'
  gem 'rswag-specs'
end

group :development do
  gem 'rails-erd'
  gem 'brakeman'
end
